/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0a05402c-0fcf-4c36-aaf8-42471a98e417",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_bajauMhsn",
    "aws_user_pools_web_client_id": "4dv1jdg4dmkr7el22cocnv58np",
    "oauth": {}
};


export default awsmobile;
